version: '3'
services:
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - python
  # db:
  #   # image: mysql:8.0
  #   # image: mysql:8.0.23
  #   image: mysql@sha256:43bf7db32d11e75d8463a8bc077f09af5fb5b84b182b1d74124ddca633093bfa
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=${DB_NAME}
  #     - MYSQL_USER=${DB_USER}
  #     - MYSQL_PASSWORD=${DB_PASS}
  #     - MYSQL_ROOT_PASSWORD=${DB_PASS}
  #     - TZ=${TZ}

  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql/initdb.d:/docker-entrypoint-initdb.d
  #     - ./mysql/db:/var/lib/mysql
  #     - ./mysql/conf.d:/etc/mysql/conf.d
  #     - ./mysql/logs:/var/log/mysql
  python:
    build: ./python
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./python:/tmp
      - ./src:/code
      - ./static:/static
    expose:
      - "8001"
    # depends_on:
    #   - db